### ISSUE TITLE
Denoに移行

### ISSUE THREAD

**Issue by windchime-yk** [windChimeYK/replaceRuby#98]
現在、`novel-support.js`はNode.jsの外部モジュールとは非依存の関係にあり、移行がさほど難しくない状態にある。
また、Denoに移行することで統一されたLinterやFormatterが享受でき、開発系依存関係の極力排除にも繋がる。単純に開発者体験が高い。
従来のNodeモジュール提供については、[dnt](https://deno.land/x/dnt@0.11.0)を使うことができるはずである。

よって、本IssueでDeno移行の可能性を探っていく

**Comment by windchime-yk** [comment]
## やるべきこと
- [x] TypeScriptファイルをnpmパッケージとしてビルド
- [x] Sassファイルをnpmパッケージフォルダにコピー
- [ ] GitHub Actionsのリリースフロー構築

**Comment by windchime-yk** [comment]
以下のようなテストファイルを設置すると、
``` typescript
import { assertEquals } from "../deps.ts";
import { convert } from "../utils/convert.ts";

Deno.test("convert - indent only", () => {
  const text = "あ\n";
  const actual = convert({
    text,
    use: {
      indent: true,
    },
  });
  const expected = '<p class="ns_indent">あ</p>';

  assertEquals<string>(actual, expected);
});
Deno.test("convert - ruby notation only", () => {
  const text = "|あ《い》";
  const actual = convert({
    text,
    use: {
      ruby: true,
    },
  });
  const expected = '<ruby class="ns_ruby">あ<rt>い</rt></ruby>';

  assertEquals<string>(actual, expected);
});
Deno.test("convert - emphasis only", () => {
  const text = "《《あ》》";
  const actual = convert({
    text,
    use: {
      emphasis: true,
    },
  });
  const expected = '<strong class="ns_emphasis">あ</strong>';

  assertEquals<string>(actual, expected);
});
```
ビルド時に以下のようなエラーが出る。
``` bash
[dnt] Transforming...
[dnt] Running npm install...

up to date, audited 7 packages in 1s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
[dnt] Building project...
[dnt] Top level await cannot be used when distributing CommonJS (See deps/deno_land/x/deno_cache_0.2.1/deno_dir.ts 9:1). Please re-organize your code to not use a top level await or only distribute an ESM module by setting the 'cjs' build option to false.
error: Uncaught (in promise) Error: Build failed due to top level await when creating CommonJS package.
        throw new Error(
              ^
    at build (https://deno.land/x/dnt@0.11.0/mod.ts:244:15)
    at async file:///Users/windchime-yk/Documents/web/novel-support.js/scripts/npm-build.ts:3:1
error: Failed at the build script
```

**Comment by windchime-yk** [comment]
テストファイルが起因のため、ビルド時にテストを実施しないことで解決。
テストはCIで実施する。

**Comment by windchime-yk** [comment]
以下事由によりnovel-support.jsを凍結とするため、Close。
- novel-support.jsという名前を変更したい（.jsがつくとURLがおかしくなる場合がある）
- rwl-devに移行したい（あまり使われていないパッケージなので作り直して移行が一番いい）
- Denoに移行したい（eslintやPrettierの構築に消耗した）
